export type AiLearningCourseSeed = {
  fa: string
  en: string
  slug: string
  metaDescription: string
}

/** Private AI tutoring courses — stored as Job rows with slug prefix `ai-`. */
export const AI_LEARNING_COURSES: AiLearningCourseSeed[] = [
  { fa: 'دوره کامل هوش مصنوعی برای مبتدیان', en: 'Complete AI for Beginners', slug: 'ai-complete-for-beginners', metaDescription: 'آموزش خصوصی هوش مصنوعی از صفر؛ مفاهیم پایه، ابزارها و پروژهٔ اول — کلاس یک‌به‌یک با مربی.' },
  { fa: 'آموزش Prompt Engineering حرفه‌ای (فارسی + انگلیسی)', en: 'Professional Prompt Engineering', slug: 'ai-prompt-engineering-pro', metaDescription: 'نوشتن پرامپت حرفه‌ای برای ChatGPT و مدل‌های زبانی؛ فارسی و انگلیسی، با تمرین عملی.' },
  { fa: 'دوره تولید محتوا با هوش مصنوعی (متن، تصویر، ویدیو)', en: 'AI Content Creation', slug: 'ai-content-creation', metaDescription: 'تولید متن، تصویر و ویدیو با AI برای شبکه‌های اجتماعی و کسب‌وکار — دوره خصوصی پروژه‌محور.' },
  { fa: 'آموزش ChatGPT و Grok برای کسب‌وکار', en: 'ChatGPT and Grok for Business', slug: 'ai-chatgpt-grok-business', metaDescription: 'کاربرد ChatGPT و Grok در فروش، پشتیبانی، بازاریابی و مدیریت — آموزش عملی برای مدیران.' },
  { fa: 'دوره برنامه‌نویسی Python با تمرکز روی AI', en: 'Python Programming for AI', slug: 'ai-python-programming', metaDescription: 'یادگیری Python از پایه تا پروژه‌های هوش مصنوعی؛ کلاس خصوصی با تمرین و بازخورد هفتگی.' },
  { fa: 'آموزش ساخت چت‌بات هوشمند با Python', en: 'Build Smart Chatbots with Python', slug: 'ai-chatbot-python', metaDescription: 'ساخت چت‌بات هوشمند با Python و API مدل‌های زبانی؛ از ایده تا استقرار.' },
  { fa: 'دوره Midjourney و تولید تصویر حرفه‌ای', en: 'Midjourney Professional Image Generation', slug: 'ai-midjourney', metaDescription: 'تولید تصویر حرفه‌ای با Midjourney؛ پرامپت، استایل و workflow برای طراحان و مارکترها.' },
  { fa: 'آموزش Stable Diffusion و مدل‌های متن به تصویر', en: 'Stable Diffusion Text-to-Image', slug: 'ai-stable-diffusion', metaDescription: 'Stable Diffusion و مدل‌های متن‌به‌تصویر؛ تنظیم، fine-tune و خروجی تجاری.' },
  { fa: 'دوره هوش مصنوعی برای تولید محتوای اینستاگرام', en: 'AI for Instagram Content', slug: 'ai-instagram-content', metaDescription: 'تولید محتوای اینستاگرام با AI؛ کپشن، تصویر، ریلز و تقویم محتوایی — دوره خصوصی.' },
  { fa: 'آموزش ساخت ابزارهای AI بدون کدنویسی (No-Code)', en: 'No-Code AI Tools', slug: 'ai-no-code-tools', metaDescription: 'ساخت ابزار هوش مصنوعی بدون کدنویسی؛ اتوماسیون و محصول با پلتفرم‌های No-Code.' },
  { fa: 'دوره کامل یادگیری ماشین (Machine Learning)', en: 'Complete Machine Learning', slug: 'ai-machine-learning', metaDescription: 'Machine Learning از مفاهیم پایه تا مدل‌سازی؛ sklearn، ارزیابی و پروژهٔ واقعی.' },
  { fa: 'آموزش Deep Learning و شبکه‌های عصبی', en: 'Deep Learning and Neural Networks', slug: 'ai-deep-learning', metaDescription: 'Deep Learning و شبکه‌های عصبی با PyTorch/TensorFlow؛ کلاس یک‌به‌یک پروژه‌محور.' },
  { fa: 'دوره Prompt Engineering برای برنامه‌نویسان', en: 'Prompt Engineering for Developers', slug: 'ai-prompt-engineering-devs', metaDescription: 'Prompt Engineering برای توسعه‌دهندگان؛ API، chain و ادغام در اپلیکیشن.' },
  { fa: 'آموزش استفاده از AI در سئو و دیجیتال مارکتینگ', en: 'AI for SEO and Digital Marketing', slug: 'ai-seo-digital-marketing', metaDescription: 'سئو و دیجیتال مارکتینگ با AI؛ تحقیق کلیدواژه، محتوا و آنالیز رقبا.' },
  { fa: 'دوره هوش مصنوعی برای دانشجویان دانشگاه', en: 'AI for University Students', slug: 'ai-university-students', metaDescription: 'هوش مصنوعی برای دانشجویان؛ پروژه، پایان‌نامه و مهارت بازار کار — آموزش خصوصی.' },
  { fa: 'آموزش ساخت دستیار صوتی فارسی با AI', en: 'Persian Voice Assistant with AI', slug: 'ai-persian-voice-assistant', metaDescription: 'ساخت دستیار صوتی فارسی با AI؛ تشخیص گفتار، TTS و سناریوهای کاربردی.' },
  { fa: 'دوره تحلیل داده با هوش مصنوعی', en: 'Data Analysis with AI', slug: 'ai-data-analysis', metaDescription: 'تحلیل داده با AI و Python؛ pandas، visualization و بینش‌سازی برای تصمیم‌گیری.' },
  { fa: 'آموزش ساخت سیستم توصیه‌گر (Recommendation System)', en: 'Recommendation Systems', slug: 'ai-recommendation-systems', metaDescription: 'ساخت سیستم توصیه‌گر؛ collaborative filtering، embedding و استقرار.' },
  { fa: 'دوره هوش مصنوعی برای مدیران و کسب‌وکارها', en: 'AI for Managers and Business', slug: 'ai-for-managers', metaDescription: 'هوش مصنوعی برای مدیران؛ استراتژی، ROI و پیاده‌سازی در سازمان — بدون نیاز به کدنویسی.' },
  { fa: 'آموزش Refactoring کد با کمک هوش مصنوعی', en: 'AI-Assisted Code Refactoring', slug: 'ai-code-refactoring', metaDescription: 'Refactoring کد با Copilot و AI؛ کیفیت، تست و مدرن‌سازی پروژه‌های قدیمی.' },
  { fa: 'دوره تولید ویدیو تبلیغاتی با AI (Runway, Pika)', en: 'AI Video Ads with Runway and Pika', slug: 'ai-video-ads-runway-pika', metaDescription: 'تولید ویدیو تبلیغاتی با Runway، Pika و ابزارهای AI — برای برند و آژانس.' },
  { fa: 'آموزش ساخت Admin Panel هوشمند با AI', en: 'Smart Admin Panel with AI', slug: 'ai-smart-admin-panel', metaDescription: 'ساخت پنل مدیریت هوشمند با AI؛ داشبورد، گزارش خودکار و اتوماسیون.' },
  { fa: 'دوره هوش مصنوعی در پزشکی و تشخیص بیماری', en: 'AI in Medical Diagnosis', slug: 'ai-medical-diagnosis', metaDescription: 'کاربرد AI در پزشکی و تشخیص؛ مفاهیم، داده و اخلاق — برای دانشجویان و متخصصان.' },
  { fa: 'آموزش نوشتن رزومه و انگیزه‌نامه با AI', en: 'Resume and Cover Letter with AI', slug: 'ai-resume-cover-letter', metaDescription: 'نوشتن رزومه و انگیزه‌نامه حرفه‌ای با AI؛ ATS، شخصی‌سازی و مصاحبه.' },
  { fa: 'دوره هوش مصنوعی برای معلمان و مدرسان', en: 'AI for Teachers', slug: 'ai-for-teachers', metaDescription: 'هوش مصنوعی برای معلمان؛ طراحی درس، ارزیابی و ابزار آموزشی هوشمند.' },
  { fa: 'آموزش ساخت اپلیکیشن با AI (Bubble + AI)', en: 'Build Apps with Bubble and AI', slug: 'ai-bubble-apps', metaDescription: 'ساخت اپلیکیشن با Bubble و ادغام AI؛ بدون کدنویسی سنگین، با منتور خصوصی.' },
  { fa: 'دوره کامل LangChain و ساخت Agentهای هوشمند', en: 'LangChain and AI Agents', slug: 'ai-langchain-agents', metaDescription: 'LangChain و Agentهای هوشمند؛ RAG، tools و استقرار agent در production.' },
  { fa: 'آموزش استفاده از Grok, Gemini و Claude', en: 'Grok Gemini and Claude', slug: 'ai-grok-gemini-claude', metaDescription: 'کار با Grok، Gemini و Claude؛ مقایسه، پرامپت و workflow حرفه‌ای.' },
  { fa: 'دوره هوش مصنوعی برای عکاسان و طراحان', en: 'AI for Photographers and Designers', slug: 'ai-for-designers', metaDescription: 'AI برای عکاسان و طراحان؛ ویرایش، تولید و workflow خلاقانه.' },
  { fa: 'آموزش ساخت CRM هوشمند با AI', en: 'Smart CRM with AI', slug: 'ai-smart-crm', metaDescription: 'ساخت CRM هوشمند با AI؛ lead scoring، اتوماسیون و گزارش فروش.' },
  { fa: 'دوره Prompt Engineering پیشرفته برای فروش', en: 'Advanced Prompt Engineering for Sales', slug: 'ai-prompt-engineering-sales', metaDescription: 'Prompt Engineering پیشرفته برای تیم فروش؛ outreach، CRM و conversion.' },
  { fa: 'آموزش هوش مصنوعی در کشاورزی هوشمند', en: 'AI in Smart Agriculture', slug: 'ai-smart-agriculture', metaDescription: 'هوش مصنوعی در کشاورزی؛ تشخیص بیماری، پیش‌بینی محصول و سنسورها.' },
  { fa: 'دوره ساخت ربات معاملاتی بورس با AI', en: 'AI Trading Bots', slug: 'ai-trading-bots', metaDescription: 'ربات معاملاتی بورس با AI؛ استراتژی، backtest و مدیریت ریسک — آموزش خصوصی.' },
  { fa: 'آموزش ویرایش عکس و ویدیو با هوش مصنوعی', en: 'AI Photo and Video Editing', slug: 'ai-photo-video-editing', metaDescription: 'ویرایش عکس و ویدیو با AI؛ retouch، upscaling و workflow حرفه‌ای.' },
  { fa: 'دوره هوش مصنوعی برای وکلا و مشاوران حقوقی', en: 'AI for Lawyers', slug: 'ai-for-lawyers', metaDescription: 'AI برای وکلا؛ تحقیق حقوقی، قرارداد و خلاصه‌سازی پرونده — با رعایت اخلاق.' },
  { fa: 'آموزش ساخت ابزارهای اتوماسیون شخصی', en: 'Personal Automation Tools with AI', slug: 'ai-personal-automation', metaDescription: 'اتوماسیون شخصی با AI؛ email، calendar و workflow روزانه.' },
  { fa: 'دوره کامل اخلاق هوش مصنوعی و مسئولیت‌پذیری', en: 'AI Ethics and Responsibility', slug: 'ai-ethics', metaDescription: 'اخلاق AI، bias، privacy و governance — دوره جامع برای تیم‌ها و مدیران.' },
  { fa: 'آموزش ساخت مدل‌های زبانی کوچک (Small LLMs)', en: 'Small Language Models', slug: 'ai-small-llms', metaDescription: 'ساخت و fine-tune مدل‌های زبانی کوچک؛ LoRA، quantization و استقرار.' },
  { fa: 'دوره هوش مصنوعی برای رستوران‌ها و کافه‌ها', en: 'AI for Restaurants and Cafes', slug: 'ai-restaurants', metaDescription: 'AI برای رستوران؛ منوی دیجیتال، پیش‌بینی موجودی و بازاریابی محلی.' },
  { fa: 'آموزش ساخت منوی دیجیتال هوشمند با AI', en: 'Smart Digital Menu with AI', slug: 'ai-digital-menu', metaDescription: 'منوی دیجیتال هوشمند با AI؛ توصیه غذا، چندزبانه و یکپارچه با POS.' },
  { fa: 'دوره برنامه‌نویسی AI با JavaScript', en: 'AI Programming with JavaScript', slug: 'ai-javascript', metaDescription: 'برنامه‌نویسی AI با JavaScript/Node؛ API مدل‌ها، chatbot وب و automation.' },
  { fa: 'آموزش ساخت چت‌بات برای وبسایت', en: 'Website Chatbot Development', slug: 'ai-website-chatbot', metaDescription: 'چت‌بات وبسایت با AI؛ widget، RAG روی محتوای سایت و CRM.' },
  { fa: 'دوره هوش مصنوعی در بازاریابی دیجیتال', en: 'AI in Digital Marketing', slug: 'ai-digital-marketing', metaDescription: 'بازاریابی دیجیتال با AI؛ کمپین، A/B test و personalization.' },
  { fa: 'آموزش ساخت داشبورد تحلیلی با AI', en: 'AI Analytics Dashboards', slug: 'ai-analytics-dashboard', metaDescription: 'داشبورد تحلیلی با AI؛ KPI، پیش‌بینی و گزارش خودکار برای مدیران.' },
  { fa: 'دوره هوش مصنوعی برای فریلنسرها', en: 'AI for Freelancers', slug: 'ai-for-freelancers', metaDescription: 'AI برای فریلنسرها؛ پیدا کردن مشتری، تحویل سریع‌تر و pricing.' },
  { fa: 'آموزش استفاده از AI در طراحی سایت و UI/UX', en: 'AI for Web Design and UI UX', slug: 'ai-ui-ux-design', metaDescription: 'طراحی UI/UX با AI؛ wireframe، prototype و handoff به توسعه.' },
  { fa: 'دوره تشخیص تقلب با هوش مصنوعی', en: 'AI Fraud Detection', slug: 'ai-fraud-detection', metaDescription: 'تشخیص تقلب با ML؛ anomaly detection و pipeline در fintech.' },
  { fa: 'آموزش ساخت سیستم نوبت‌دهی هوشمند', en: 'Smart Appointment Booking', slug: 'ai-appointment-booking', metaDescription: 'سیستم نوبت‌دهی هوشمند با AI؛ کلینیک، سالن و مشاوره.' },
  { fa: 'دوره هوش مصنوعی برای مدیران محصول', en: 'AI for Product Managers', slug: 'ai-for-product-managers', metaDescription: 'AI برای PM؛ roadmap، user research و feature با مدل‌های زبانی.' },
  { fa: 'آموزش ساخت ابزارهای افزایش بهره‌وری', en: 'AI Productivity Tools', slug: 'ai-productivity-tools', metaDescription: 'ابزار بهره‌وری شخصی و تیمی با AI؛ notes، tasks و meeting summary.' },
  { fa: 'دوره کامل Computer Vision با Python', en: 'Computer Vision with Python', slug: 'ai-computer-vision', metaDescription: 'Computer Vision با OpenCV و deep learning؛ detection، OCR و پروژه.' },
  { fa: 'آموزش ساخت تشخیص پلاک خودرو با AI', en: 'License Plate Recognition with AI', slug: 'ai-license-plate-recognition', metaDescription: 'تشخیص پلاک خودرو با AI؛ camera pipeline و استقرار edge.' },
  { fa: 'دوره هوش مصنوعی در آموزش آنلاین', en: 'AI in Online Education', slug: 'ai-online-education', metaDescription: 'AI در EdTech؛ personalization، quiz و tutor هوشمند.' },
  { fa: 'آموزش ساخت بازی با هوش مصنوعی', en: 'Game Development with AI', slug: 'ai-game-development', metaDescription: 'ساخت بازی با AI؛ NPC هوشمند، procedural content و Unity/Godot.' },
  { fa: 'دوره Prompt Engineering برای نویسندگان', en: 'Prompt Engineering for Writers', slug: 'ai-prompt-engineering-writers', metaDescription: 'Prompt Engineering برای نویسندگان؛ داستان، copywriting و ویرایش.' },
  { fa: 'آموزش ساخت دستیار شخصی AI', en: 'Personal AI Assistant', slug: 'ai-personal-assistant', metaDescription: 'دستیار شخصی AI؛ calendar، email و automation روی دادهٔ خودتان.' },
  { fa: 'دوره هوش مصنوعی برای حسابداران', en: 'AI for Accountants', slug: 'ai-for-accountants', metaDescription: 'AI برای حسابداری؛ invoice، reconciliation و گزارش مالی.' },
  { fa: 'آموزش بهینه‌سازی کد با GitHub Copilot', en: 'GitHub Copilot Code Optimization', slug: 'ai-github-copilot', metaDescription: 'GitHub Copilot و AI coding؛ سرعت توسعه، review و best practices.' },
  { fa: 'دوره ساخت Marketplace با AI', en: 'Build Marketplace with AI', slug: 'ai-marketplace', metaDescription: 'Marketplace با AI؛ matching، search و moderation — از MVP تا scale.' },
  { fa: 'آموزش هوش مصنوعی در گردشگری و هتلداری', en: 'AI in Tourism and Hospitality', slug: 'ai-tourism-hospitality', metaDescription: 'AI در گردشگری؛ chatbot رزرو، recommendation و تجربه مهمان.' },
  { fa: 'دوره تحلیل احساسات مشتریان با AI', en: 'Customer Sentiment Analysis', slug: 'ai-sentiment-analysis', metaDescription: 'تحلیل احساسات مشتری با NLP؛ review، social و dashboard.' },
  { fa: 'آموزش ساخت ابزار ترجمه همزمان فارسی', en: 'Persian Real-Time Translation', slug: 'ai-persian-translation', metaDescription: 'ترجمه همزمان فارسی با AI؛ speech-to-speech و subtitle.' },
  { fa: 'دوره هوش مصنوعی برای استارتاپ‌ها', en: 'AI for Startups', slug: 'ai-for-startups', metaDescription: 'AI برای استارتاپ؛ MVP سریع، pitch و product-market fit.' },
  { fa: 'آموزش ساخت سیستم مدیریت پروژه هوشمند', en: 'Smart Project Management with AI', slug: 'ai-project-management', metaDescription: 'مدیریت پروژه هوشمند با AI؛ planning، risk و report خودکار.' },
  { fa: 'دوره AI برای تولید موسیقی و صدا', en: 'AI Music and Audio Production', slug: 'ai-music-audio', metaDescription: 'تولید موسیقی و صدا با AI؛ Suno، voice clone و podcast.' },
  { fa: 'آموزش ساخت ابزارهای آموزشی هوشمند', en: 'Smart Educational Tools', slug: 'ai-educational-tools', metaDescription: 'ابزار آموزشی هوشمند با AI؛ quiz، tutor و adaptive learning.' },
  { fa: 'دوره هوش مصنوعی در صنعت نفت و گاز', en: 'AI in Oil and Gas', slug: 'ai-oil-gas', metaDescription: 'AI در نفت و گاز؛ predictive maintenance و تحلیل دادهٔ صنعتی.' },
  { fa: 'آموزش ساخت ربات تلگرام هوشمند', en: 'Telegram AI Bot', slug: 'ai-telegram-bot', metaDescription: 'ربات تلگرام هوشمند با AI؛ پشتیبانی، فروش و automation.' },
  { fa: 'دوره کامل Vector Database و RAG', en: 'Vector Database and RAG', slug: 'ai-vector-db-rag', metaDescription: 'Vector DB و RAG؛ embedding، retrieval و chatbot روی اسناد.' },
  { fa: 'آموزش استفاده از AI در طراحی لباس و مد', en: 'AI in Fashion Design', slug: 'ai-fashion-design', metaDescription: 'طراحی لباس و مد با AI؛ sketch، pattern و trend analysis.' },
  { fa: 'دوره هوش مصنوعی برای روانشناسان', en: 'AI for Psychologists', slug: 'ai-for-psychologists', metaDescription: 'AI برای روانشناسان؛ note-taking، research و ابزار کمکی — با رعایت ethics.' },
  { fa: 'آموزش ساخت سیستم هوشمند انبار', en: 'Smart Warehouse with AI', slug: 'ai-smart-warehouse', metaDescription: 'انبار هوشمند با AI؛ inventory، forecasting و routing.' },
  { fa: 'دوره AI برای مشاوران املاک', en: 'AI for Real Estate Agents', slug: 'ai-real-estate', metaDescription: 'AI برای املاک؛ listing، valuation و lead generation.' },
  { fa: 'آموزش ساخت گزارش‌های خودکار مدیریتی', en: 'Automated Management Reports', slug: 'ai-management-reports', metaDescription: 'گزارش مدیریتی خودکار با AI؛ Excel، BI و executive summary.' },
  { fa: 'دوره هوش مصنوعی در امنیت سایبری', en: 'AI in Cybersecurity', slug: 'ai-cybersecurity', metaDescription: 'AI در امنیت سایبری؛ threat detection، log analysis و SOC.' },
  { fa: 'آموزش ساخت AI Coach شخصی (تناسب اندام)', en: 'Personal AI Fitness Coach', slug: 'ai-fitness-coach', metaDescription: 'AI Coach تناسب اندام؛ برنامه تمرین، nutrition و tracking.' },
  { fa: 'دوره Prompt Engineering برای دانشجویان', en: 'Prompt Engineering for Students', slug: 'ai-prompt-engineering-students', metaDescription: 'Prompt Engineering برای دانشجویان؛ تحقیق، خلاصه و پروژهٔ درسی.' },
  { fa: 'آموزش ساخت ابزار خلاصه‌سازی مقالات', en: 'Article Summarization Tools', slug: 'ai-article-summarizer', metaDescription: 'خلاصه‌سازی مقاله و PDF با AI؛ research workflow و citation.' },
  { fa: 'دوره هوش مصنوعی در حقوق و قراردادها', en: 'AI in Legal Contracts', slug: 'ai-legal-contracts', metaDescription: 'AI در قرارداد و حقوق؛ draft، review و clause extraction.' },
  { fa: 'آموزش ساخت سیستم تشخیص بیماری گیاهان', en: 'Plant Disease Detection', slug: 'ai-plant-disease', metaDescription: 'تشخیص بیماری گیاه با computer vision؛ dataset و mobile app.' },
  { fa: 'دوره کامل MLOps و استقرار مدل‌ها', en: 'MLOps and Model Deployment', slug: 'ai-mlops', metaDescription: 'MLOps؛ CI/CD مدل، monitoring و scale در production.' },
  { fa: 'آموزش استفاده از AI در پژوهش دانشگاهی', en: 'AI in Academic Research', slug: 'ai-academic-research', metaDescription: 'AI در پژوهش؛ literature review، data analysis و writing ethics.' },
  { fa: 'دوره هوش مصنوعی برای مدیران مالی', en: 'AI for CFOs and Finance', slug: 'ai-for-finance', metaDescription: 'AI برای مالی؛ forecasting، budgeting و risk analysis.' },
  { fa: 'آموزش ساخت چت‌بات مشاوره تحصیلی', en: 'Educational Counseling Chatbot', slug: 'ai-education-counseling-bot', metaDescription: 'چت‌بات مشاوره تحصیلی با AI؛ مسیر شغلی و انتخاب رشته.' },
  { fa: 'دوره AI برای کسب‌وکارهای کوچک و متوسط', en: 'AI for SMBs', slug: 'ai-for-smb', metaDescription: 'AI برای SME؛ automation ارزان، marketing و customer service.' },
  { fa: 'آموزش ساخت ابزار ویرایش متن فارسی', en: 'Persian Text Editing with AI', slug: 'ai-persian-text-editor', metaDescription: 'ویرایش و غلط‌گیری متن فارسی با AI؛ tone، SEO و formal writing.' },
  { fa: 'دوره هوش مصنوعی در تبلیغات گوگل و اینستاگرام', en: 'AI for Google and Instagram Ads', slug: 'ai-paid-ads', metaDescription: 'تبلیغات Google و Instagram با AI؛ creative، targeting و optimization.' },
  { fa: 'آموزش ساخت سیستم هوشمند رزرو', en: 'Smart Reservation System', slug: 'ai-reservation-system', metaDescription: 'سیستم رزرو هوشمند با AI؛ hotel، restaurant و service booking.' },
  { fa: 'دوره Refactoring و مدرن‌سازی پروژه با AI', en: 'Legacy Modernization with AI', slug: 'ai-legacy-modernization', metaDescription: 'مدرن‌سازی legacy با AI؛ migration plan، test و refactor امن.' },
  { fa: 'آموزش ساخت Admin Panel با کمک هوش مصنوعی', en: 'Admin Panel with AI Assistance', slug: 'ai-admin-panel-assisted', metaDescription: 'Admin Panel با کمک AI؛ CRUD سریع، dashboard و role-based access.' },
  { fa: 'دوره هوش مصنوعی برای والدین و آموزش کودکان', en: 'AI for Parents and Kids Education', slug: 'ai-for-parents', metaDescription: 'AI برای والدین؛ یادگیری امن کودک، homework help و digital literacy.' },
  { fa: 'آموزش ساخت ابزار مدیریت زمان و بهره‌وری', en: 'Time Management Tools with AI', slug: 'ai-time-management', metaDescription: 'مدیریت زمان با AI؛ prioritization، focus و habit tracking.' },
  { fa: 'دوره AI برای تولید پادکست و محتوای صوتی', en: 'AI Podcast and Audio Content', slug: 'ai-podcast-production', metaDescription: 'پادکست و محتوای صوتی با AI؛ script، edit و distribution.' },
  { fa: 'آموزش ساخت سیستم پیشنهاد محصول فروشگاه', en: 'E-commerce Product Recommendations', slug: 'ai-ecommerce-recommendations', metaDescription: 'Recommendation فروشگاه آنلاین با AI؛ upsell و personalization.' },
  { fa: 'دوره هوش مصنوعی در محیط زیست و انرژی', en: 'AI in Environment and Energy', slug: 'ai-environment-energy', metaDescription: 'AI در انرژی و محیط زیست؛ optimization، forecast و sustainability.' },
  { fa: 'آموزش ساخت ابزارهای قانونی و حقوقی AI', en: 'Legal AI Tools', slug: 'ai-legal-tools', metaDescription: 'ابزار حقوقی AI؛ contract analyzer و compliance checker.' },
  { fa: 'دوره کامل AI Agents و Autonomous Systems', en: 'AI Agents and Autonomous Systems', slug: 'ai-agents-autonomous', metaDescription: 'Agentهای خودمختار؛ planning، multi-agent و production patterns.' },
  { fa: 'آموزش هوش مصنوعی برای المپیاد و رقابت‌های ملی', en: 'AI for Olympiad and Competitions', slug: 'ai-olympiad-prep', metaDescription: 'آمادگی المپیاد AI و رقابت‌های ملی؛ algorithm و ML intensive.' },
  { fa: 'دوره ساخت استارتاپ هوش مصنوعی از صفر', en: 'Build AI Startup from Zero', slug: 'ai-startup-from-zero', metaDescription: 'استارتاپ AI از ایده تا MVP؛ validation، tech stack و fundraising.' },
  { fa: 'برنامه منتورینگ و بوت‌کمپ کامل هوش مصنوعی (۳ ماهه)', en: '3-Month AI Mentoring Bootcamp', slug: 'ai-3-month-bootcamp', metaDescription: 'بوت‌کمپ ۳ ماهه AI با منتور اختصاصی؛ از پایه تا پروژه و آماده‌سازی شغلی.' },
]
