export type SoftwareProductSeed = {
  fa: string
  en: string
  slug: string
  metaDescription: string
}

export const SOFTWARE_PRODUCTS: SoftwareProductSeed[] = [
  { fa: 'CRM هوشمند مدیریت مشتریان', en: 'Smart CRM', slug: 'software-crm-smart', metaDescription: 'طراحی CRM اختصاصی با AI — مدیریت لید، فروش، پیگیری و گزارش برای تیم شما.' },
  { fa: 'سیستم حسابداری و فاکتور آنلاین', en: 'Online Accounting and Invoicing', slug: 'software-accounting-invoice', metaDescription: 'نرم‌افزار حسابداری و صدور فاکتور آنلاین — یکپارچه با مالیات و درگاه پرداخت.' },
  { fa: 'پنل مدیریت فروش و انبار', en: 'Sales and Inventory Panel', slug: 'software-sales-inventory', metaDescription: 'پنل فروش و انبارداری — موجودی، سفارش، تأمین‌کننده و گزارش real-time.' },
  { fa: 'چت‌بات هوشمند پشتیبانی مشتریان', en: 'AI Customer Support Chatbot', slug: 'software-support-chatbot', metaDescription: 'چت‌بات پشتیبانی ۲۴/۷ با AI — وب، تلگرام و واتساپ؛ کاهش هزینه call center.' },
  { fa: 'سیستم نوبت‌دهی هوشمند پزشکی', en: 'Medical Appointment System', slug: 'software-medical-booking', metaDescription: 'نوبت‌دهی آنلاین مطب و کلینیک — SMS، تقویم پزشک و پنل منشی.' },
  { fa: 'پنل صرافی ارز دیجیتال', en: 'Crypto Exchange Panel', slug: 'software-crypto-exchange', metaDescription: 'پلتفرم صرافی ارز دیجیتال — KYC، wallet، order book و امنیت سطح بالا.' },
  { fa: 'کیف پول ارز دیجیتال با امنیت AI', en: 'AI-Secured Crypto Wallet', slug: 'software-crypto-wallet', metaDescription: 'کیف پول رمز ارز با لایه امنیتی AI — multi-sig و مانیتورینگ تقلب.' },
  { fa: 'سیستم رزرواسیون هتل و اقامتگاه بوم‌گردی', en: 'Hotel and Eco-Lodge Booking', slug: 'software-hotel-booking', metaDescription: 'رزرو آنلاین هتل و بوم‌گردی — تقویم، پرداخت و پنل پذیرش.' },
  { fa: 'منوی دیجیتال هوشمند رستوران و کافه', en: 'Smart Restaurant Digital Menu', slug: 'software-restaurant-menu', metaDescription: 'منوی دیجیتال QR — سفارش آنلاین، آشپزخانه و پرداخت برای رستوران و کافه.' },
  { fa: 'نرم‌افزار مدیریت آرایشگاه و سالن زیبایی', en: 'Salon Management Software', slug: 'software-salon-management', metaDescription: 'مدیریت نوبت، پرسنل، خدمات و باشگاه مشتری برای سالن زیبایی.' },
  { fa: 'پنل مدیریت کلینیک زیبایی', en: 'Beauty Clinic Panel', slug: 'software-beauty-clinic', metaDescription: 'پنل کلینیک زیبایی — پرونده بیمار، جلسات، پرداخت و CRM.' },
  { fa: 'سیستم سفارش آنلاین رستوران و فست‌فود', en: 'Restaurant Online Ordering', slug: 'software-restaurant-ordering', metaDescription: 'سفارش آنلاین غذا — delivery، pickup، kitchen display و درگاه.' },
  { fa: 'داشبورد مدیریتی کسب‌وکار (Business Intelligence)', en: 'Business Intelligence Dashboard', slug: 'software-bi-dashboard', metaDescription: 'داشبورد BI — KPI، نمودار زنده و گزارش مدیریتی از داده‌های شما.' },
  { fa: 'Refactoring و بهینه‌سازی کدبیس موجود', en: 'Codebase Refactoring', slug: 'software-code-refactoring', metaDescription: 'بازنویسی و بهینه‌سازی کد legacy — performance، امنیت و maintainability.' },
  { fa: 'ایجاد Admin Panel حرفه‌ای و ریسپانسیو', en: 'Professional Admin Panel', slug: 'software-admin-panel', metaDescription: 'Admin Panel ریسپانسیو — role-based، CRUD، گزارش و API.' },
  { fa: 'سیستم مدیریت مدرسه و آموزشگاه', en: 'School Management System', slug: 'software-school-management', metaDescription: 'مدیریت مدرسه — نمرات، حضور، شهریه، اولیا و پورتال دانش‌آموز.' },
  { fa: 'پلتفرم آموزش آنلاین هوشمند (LMS)', en: 'Smart LMS Platform', slug: 'software-lms-platform', metaDescription: 'LMS اختصاصی — ویدئو، آزمون، گواهی و پنل مدرس با AI.' },
  { fa: 'نرم‌افزار حضور و غیاب هوشمند کارکنان', en: 'Smart Attendance System', slug: 'software-attendance', metaDescription: 'حضور و غیاب — biometric، shift، گزارش HR و یکپارچگی حقوق.' },
  { fa: 'سیستم مدیریت پروژه و تسک‌ها', en: 'Project and Task Management', slug: 'software-project-management', metaDescription: 'مدیریت پروژه — Kanban، Gantt، time tracking و گزارش تیم.' },
  { fa: 'ابزار افزایش بهره‌وری تیم (Productivity Dashboard)', en: 'Team Productivity Dashboard', slug: 'software-productivity-dashboard', metaDescription: 'داشبورد بهره‌وری تیم — OKR، tasks و analytics.' },
  { fa: 'منوی دیجیتال تعاملی برای کافه و قهوه‌فروشی', en: 'Interactive Cafe Menu', slug: 'software-cafe-menu', metaDescription: 'منوی تعاملی کافه — سفارش، loyalty و پرداخت بدون صف.' },
  { fa: 'سیستم مدیریت موجودی انبار هوشمند', en: 'Smart Warehouse Inventory', slug: 'software-warehouse-inventory', metaDescription: 'انبارداری هوشمند — barcode، reorder point و گزارش موجودی.' },
  { fa: 'AI تولید محتوای فارسی (متن، کپشن، مقاله)', en: 'Persian AI Content Generator', slug: 'software-ai-content-fa', metaDescription: 'پلتفرم تولید محتوای فارسی با AI — مقاله، کپشن و SEO برای برند شما.' },
  { fa: 'AI تولید تصویر و بنر تبلیغاتی', en: 'AI Ad Banner Generator', slug: 'software-ai-image-ads', metaDescription: 'تولید بنر و تصویر تبلیغاتی با AI — یکپارچه با کمپین مارکتینگ.' },
  { fa: 'سیستم تشخیص پلاک خودرو', en: 'License Plate Recognition', slug: 'software-anpr', metaDescription: 'ANPR و تشخیص پلاک — پارکینگ، امنیت و log خودرو.' },
  { fa: 'داشبورد تحلیلی فروش و گزارش‌گیری', en: 'Sales Analytics Dashboard', slug: 'software-sales-analytics', metaDescription: 'تحلیل فروش — funnel، cohort و پیش‌بینی revenue.' },
  { fa: 'پنل مدیریت مشاور املاک', en: 'Real Estate Agent Panel', slug: 'software-real-estate', metaDescription: 'CRM املاک — فایل، بازدید، قرارداد و commission.' },
  { fa: 'سیستم پرداخت آنلاین و درگاه پرداخت', en: 'Online Payment Gateway Integration', slug: 'software-payment-gateway', metaDescription: 'یکپارچه‌سازی درگاه — Zarinpal، IDPay و wallet داخلی.' },
  { fa: 'نرم‌افزار مدیریت داروخانه', en: 'Pharmacy Management', slug: 'software-pharmacy', metaDescription: 'مدیریت داروخانه — نسخه، موجودی، expiry و بیمه.' },
  { fa: 'چت‌بات فروش هوشمند', en: 'AI Sales Chatbot', slug: 'software-sales-chatbot', metaDescription: 'چت‌بات فروش — lead qualification و booking خودکار.' },
  { fa: 'سیستم رزرو اتاق فرار', en: 'Escape Room Booking', slug: 'software-escape-room', metaDescription: 'رزرو اتاق فرار — slot، تیم، پرداخت و CRM.' },
  { fa: 'پنل مدیریت نمایشگاه ماشین', en: 'Car Dealership Panel', slug: 'software-car-dealership', metaDescription: 'مدیریت نمایشگاه — inventory، test drive و financing.' },
  { fa: 'نرم‌افزار مدیریت تعمیرگاه خودرو', en: 'Auto Repair Shop Software', slug: 'software-auto-repair', metaDescription: 'تعمیرگاه — work order، parts، SMS و invoice.' },
  { fa: 'AI پیش‌بینی فروش و موجودی', en: 'AI Sales and Inventory Forecast', slug: 'software-ai-forecast', metaDescription: 'پیش‌بینی demand با ML — کاهش overstock و stockout.' },
  { fa: 'سیستم مدیریت تور و گردشگری', en: 'Tour Management System', slug: 'software-tour-management', metaDescription: 'مدیریت تور — itinerary، booking، guide و payment.' },
  { fa: 'پنل چندفروشنده (Marketplace)', en: 'Multi-Vendor Marketplace', slug: 'software-marketplace', metaDescription: 'مارکت‌پلیس — vendor panel، commission و escrow.' },
  { fa: 'ابزار Refactoring کد legacy', en: 'Legacy Code Refactoring Tool', slug: 'software-legacy-refactor', metaDescription: 'مهاجرت legacy — monolith to microservices، test coverage.' },
  { fa: 'Admin Panel برای فروشگاه‌های آنلاین', en: 'E-commerce Admin Panel', slug: 'software-ecommerce-admin', metaDescription: 'پنل فروشگاه — محصول، سفارش، shipping و promotion.' },
  { fa: 'سیستم هوشمند مدیریت ناوگان حمل‌ونقل', en: 'Fleet Management System', slug: 'software-fleet-management', metaDescription: 'ناوگان — GPS، maintenance، route و fuel.' },
  { fa: 'ابزار افزایش بهره‌وری شخصی (Personal Productivity AI)', en: 'Personal Productivity AI', slug: 'software-personal-productivity', metaDescription: 'دستیار بهره‌وری — tasks، calendar AI و focus.' },
  { fa: 'منوی دیجیتال با QR Code برای کافه', en: 'QR Digital Menu for Cafe', slug: 'software-qr-cafe-menu', metaDescription: 'منوی QR — بدون اپ، سفارش سریع و آنalytics.' },
  { fa: 'سیستم مدیریت کتاب‌فروشی آنلاین', en: 'Online Bookstore System', slug: 'software-bookstore', metaDescription: 'کتاب‌فروشی آنلاین — ISBN، inventory و pre-order.' },
  { fa: 'نرم‌افزار مدیریت جواهرات و طلا', en: 'Jewelry and Gold Shop Software', slug: 'software-jewelry', metaDescription: 'طلافروشی — وزن، عیار، invoice و installment.' },
  { fa: 'AI تحلیل نظرات مشتریان (Sentiment Analysis)', en: 'Customer Sentiment Analysis', slug: 'software-sentiment-analysis', metaDescription: 'تحلیل sentiment — review، social و alert منفی.' },
  { fa: 'سیستم هوشمند استخدام و غربالگری رزومه', en: 'AI Recruitment System', slug: 'software-recruitment-ai', metaDescription: 'ATS با AI — parse رزومه، score و interview scheduling.' },
  { fa: 'پنل مدیریت آموزشگاه زبان و کنکور', en: 'Language and Exam Prep Institute Panel', slug: 'software-language-institute', metaDescription: 'آموزشگاه — کلاس، شهریه، حضور و portal.' },
  { fa: 'نرم‌افزار مدیریت استخر و باشگاه ورزشی', en: 'Pool and Gym Management', slug: 'software-gym-pool', metaDescription: 'باشگاه — membership، check-in و personal training.' },
  { fa: 'AI تولید ویدیو تبلیغاتی کوتاه', en: 'AI Short Video Ads', slug: 'software-ai-video-ads', metaDescription: 'ویدیو تبلیغاتی AI — template brand و export social.' },
  { fa: 'سیستم مدیریت چاپخانه و خدمات چاپ', en: 'Print Shop Management', slug: 'software-print-shop', metaDescription: 'چاپخانه — quote، order، production و delivery.' },
  { fa: 'داشبورد مالی و حسابداری هوشمند', en: 'Smart Finance Dashboard', slug: 'software-finance-dashboard', metaDescription: 'داشبورد مالی — cash flow، P&L و budget vs actual.' },
  { fa: 'پنل مدیریت بستنی‌فروشی و دسر', en: 'Ice Cream Shop Panel', slug: 'software-ice-cream-shop', metaDescription: 'بستنی‌فروشی — menu، inventory و franchise.' },
  { fa: 'سیستم نوبت‌دهی هوشمند دندانپزشکی', en: 'Dental Appointment System', slug: 'software-dental-booking', metaDescription: 'نوبت دندانپزشکی — treatment plan و reminder SMS.' },
  { fa: 'ابزار بهینه‌سازی سئو سایت با AI', en: 'AI SEO Optimization Tool', slug: 'software-ai-seo-tool', metaDescription: 'سئو با AI — audit، content suggestion و rank tracking.' },
  { fa: 'پنل مدیریت آژانس مسافرتی', en: 'Travel Agency Panel', slug: 'software-travel-agency', metaDescription: 'آژانس مسافرتی — package، visa و commission.' },
  { fa: 'نرم‌افزار مدیریت عکاسی و آتلیه', en: 'Photography Studio Software', slug: 'software-photo-studio', metaDescription: 'آتلیه — booking، gallery proof و contract.' },
  { fa: 'سیستم هوشمند کشاورزی و گلخانه', en: 'Smart Agriculture System', slug: 'software-smart-agriculture', metaDescription: 'کشاورزی IoT — sensor، irrigation و yield forecast.' },
  { fa: 'Admin Panel برای شرکت‌های دانش‌بنیان', en: 'Knowledge-Based Company Admin', slug: 'software-knowledge-company-admin', metaDescription: 'پنل دانش‌بنیان — project، grant و IP tracking.' },
  { fa: 'ابزار افزایش سرعت وبسایت (Performance Optimization)', en: 'Website Performance Optimization', slug: 'software-web-performance', metaDescription: 'بهینه‌سازی سرعت — Core Web Vitals و CDN setup.' },
  { fa: 'سیستم مدیریت رویداد و نمایشگاه', en: 'Event Management System', slug: 'software-event-management', metaDescription: 'رویداد — ticket، booth، attendee و live dashboard.' },
  { fa: 'AI دستیار صوتی فارسی', en: 'Persian Voice AI Assistant', slug: 'software-persian-voice-ai', metaDescription: 'دستیار صوتی فارسی — STT/TTS و integration call center.' },
  { fa: 'پنل مدیریت سوپرمارکت آنلاین', en: 'Online Supermarket Panel', slug: 'software-online-supermarket', metaDescription: 'سوپرمارکت آنلاین — picker app، delivery slot و inventory.' },
  { fa: 'نرم‌افزار مدیریت قنادی و شیرینی‌پزی', en: 'Pastry Shop Management', slug: 'software-pastry-shop', metaDescription: 'قنادی — custom cake order، recipe و production.' },
  { fa: 'سیستم هوشمند پارکینگ', en: 'Smart Parking System', slug: 'software-smart-parking', metaDescription: 'پارکینگ — ANPR، payment و occupancy map.' },
  { fa: 'ابزار تولید گزارش خودکار مدیریتی', en: 'Automated Management Reports', slug: 'software-auto-reports', metaDescription: 'گزارش خودکار — PDF/email scheduled از داده live.' },
  { fa: 'Refactoring و مهاجرت به فریم‌ورک جدید', en: 'Framework Migration Refactoring', slug: 'software-framework-migration', metaDescription: 'مهاجرت React/Vue/Next — zero-downtime plan.' },
  { fa: 'پنل مدیریت لوازم خانگی و فروشگاهی', en: 'Home Appliance Retail Panel', slug: 'software-appliance-retail', metaDescription: 'فروش لوازم خانگی — warranty، install و CRM.' },
  { fa: 'سیستم مدیریت روانشناس و مشاور', en: 'Therapist Practice Management', slug: 'software-therapy-practice', metaDescription: 'مشاور — session notes، billing و telehealth.' },
  { fa: 'AI پیشنهاد محصول (Recommendation Engine)', en: 'Product Recommendation Engine', slug: 'software-recommendation-engine', metaDescription: 'Recommendation — collaborative filtering در فروشگاه شما.' },
  { fa: 'نرم‌افزار مدیریت هتل و اقامتگاه', en: 'Hotel Property Management', slug: 'software-hotel-pms', metaDescription: 'PMS هتل — room، housekeeping و channel manager.' },
  { fa: 'داشبورد هوشمند برای کارخانه‌ها', en: 'Factory Smart Dashboard', slug: 'software-factory-dashboard', metaDescription: 'کارخانه — OEE، downtime و production KPI.' },
  { fa: 'منوی دیجیتال هوشمند با سفارش آنلاین برای رستوران', en: 'Restaurant Smart Menu with Ordering', slug: 'software-restaurant-smart-order', metaDescription: 'منو + سفارش + پرداخت — all-in-one رستوران.' },
  { fa: 'سیستم مدیریت باشگاه بدنسازی', en: 'Gym Management System', slug: 'software-gym-management', metaDescription: 'باشگاه بدنسازی — access control و PT scheduling.' },
  { fa: 'پنل CRM برای شرکت‌های خدماتی', en: 'Service Company CRM', slug: 'software-service-crm', metaDescription: 'CRM خدماتی — ticket، SLA و field service.' },
  { fa: 'AI تشخیص بیماری پوست و زیبایی', en: 'AI Skin Condition Detection', slug: 'software-ai-skin-detection', metaDescription: 'تشخیص پوست با AI — triage و photo analysis.' },
  { fa: 'ابزار مدیریت وظایف روزانه تیم', en: 'Daily Team Task Manager', slug: 'software-daily-tasks', metaDescription: 'وظایف روزانه — standup، priority و burndown.' },
  { fa: 'سیستم پرداخت قسطی آنلاین', en: 'Online Installment Payment', slug: 'software-installment-payment', metaDescription: 'فروش قسطی — credit check، schedule و reminder.' },
  { fa: 'پنل مدیریت صادرات و واردات', en: 'Import Export Management Panel', slug: 'software-import-export', metaDescription: 'تجارت — shipment، customs و document.' },
  { fa: 'نرم‌افزار مدیریت آزمایشگاه پزشکی', en: 'Medical Lab Management', slug: 'software-medical-lab', metaDescription: 'LIS آزمایشگاه — sample، result و HL7.' },
  { fa: 'AI خلاصه‌سازی اسناد و قراردادها', en: 'AI Document Summarization', slug: 'software-ai-document-summary', metaDescription: 'خلاصه قرارداد و PDF — legal review assist.' },
  { fa: 'Admin Panel با دسترسی چندسطحی (Multi-role)', en: 'Multi-Role Admin Panel', slug: 'software-multi-role-admin', metaDescription: 'RBAC admin — permission granular و audit trail.' },
  { fa: 'سیستم هوشمند کنترل مصرف انرژی', en: 'Smart Energy Management', slug: 'software-energy-management', metaDescription: 'Energy — meter، alert و cost optimization.' },
  { fa: 'ابزار مدیریت کمپین تبلیغاتی', en: 'Ad Campaign Manager', slug: 'software-ad-campaign', metaDescription: 'کمپین — multi-channel، budget و ROI dashboard.' },
  { fa: 'پنل فروش زعفران و محصولات کشاورزی', en: 'Saffron and Agri Products Panel', slug: 'software-saffron-sales', metaDescription: 'فروش زعفران — traceability، export و B2B portal.' },
  { fa: 'نرم‌افزار مدیریت مهدکودک و کودکستان', en: 'Kindergarten Management', slug: 'software-kindergarten', metaDescription: 'مهدکودک — attendance، parent app و activity log.' },
  { fa: 'AI بهینه‌سازی مسیر تحویل کالا', en: 'AI Delivery Route Optimization', slug: 'software-delivery-route-ai', metaDescription: 'مسیربندی delivery — TSP و live driver app.' },
  { fa: 'سیستم رزرو بلیت و رویداد', en: 'Ticket and Event Booking', slug: 'software-ticket-booking', metaDescription: 'بلیت — seat map، promo code و check-in QR.' },
  { fa: 'داشبورد تحلیلی اینستاگرام و شبکه‌های اجتماعی', en: 'Social Media Analytics Dashboard', slug: 'software-social-analytics', metaDescription: 'analytics social — engagement، competitor و report.' },
  { fa: 'Refactoring کد frontend و backend', en: 'Frontend Backend Refactoring', slug: 'software-fe-be-refactor', metaDescription: 'refactor full-stack — API versioning و test suite.' },
  { fa: 'پنل مدیریت شعب شرکت‌ها', en: 'Multi-Branch Company Panel', slug: 'software-multi-branch', metaDescription: 'چند شعبه — consolidated report و local inventory.' },
  { fa: 'سیستم هوشمند مشاوره تحصیلی', en: 'Educational Counseling System', slug: 'software-education-counseling', metaDescription: 'مشاوره تحصیلی — aptitude test و university match.' },
  { fa: 'ابزار تولید لوگو و هویت بصری با AI', en: 'AI Brand Identity Generator', slug: 'software-ai-brand-identity', metaDescription: 'برندینگ AI — logo variant و style guide export.' },
  { fa: 'نرم‌افزار مدیریت تعمیر لوازم خانگی', en: 'Home Appliance Repair Software', slug: 'software-appliance-repair', metaDescription: 'تعمیر در منزل — dispatch، parts و warranty.' },
  { fa: 'پنل مدیریت خدمات نظافت', en: 'Cleaning Service Panel', slug: 'software-cleaning-service', metaDescription: 'نظافت — booking، crew assign و quality check.' },
  { fa: 'AI پیش‌بینی روند بازار (بورس، ارز، طلا)', en: 'AI Market Trend Prediction', slug: 'software-ai-market-prediction', metaDescription: 'پیش‌بینی بازار — signal dashboard (not financial advice).' },
  { fa: 'سیستم مدیریت وام و اعتباری', en: 'Loan and Credit Management', slug: 'software-loan-management', metaDescription: 'وام — application، scoring و collection workflow.' },
  { fa: 'منوی دیجیتال برای فودکورت و فست‌فود', en: 'Food Court Digital Menu', slug: 'software-food-court-menu', metaDescription: 'فودکورت — multi-vendor menu و unified payment.' },
  { fa: 'ابزار افزایش تبدیل فروش (Conversion Rate Optimization)', en: 'CRO Tool', slug: 'software-cro-tool', metaDescription: 'CRO — A/B test، heatmap integration و funnel fix.' },
  { fa: 'پنل مدیریت استارتاپ و شرکت دانش‌بنیان', en: 'Startup Management Panel', slug: 'software-startup-panel', metaDescription: 'استارتاپ — OKR، cap table و investor update.' },
  { fa: 'سیستم هوشمند پشتیبانی ۲۴ ساعته', en: '24/7 Smart Support System', slug: 'software-24-7-support', metaDescription: 'پشتیبانی ۲۴/۷ — ticket، chatbot و knowledge base.' },
  { fa: 'داشبورد کامل هوش مصنوعی کسب‌وکار (All-in-One AI Dashboard)', en: 'All-in-One AI Business Dashboard', slug: 'software-ai-business-dashboard', metaDescription: 'داشبورد AI یکپارچه — chat، analytics، automation و reports.' },
]
